apiVersion: v2
name: bob
description: Bash on Board! - General purpose container for Kubernetes
type: application
icon: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-horizontal-color.png

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: v0.9.12
appVersion: v0.9.12
home: https://262life.github.io/bob
sources:
- https://github.com/262life/bob
maintainers:
- name: rsliotta
  email: bob@262.life
keywords:
- bob
- 262life
- bash
